const skills=[
  ['Python','programming','fa-brands fa-python',45],['JavaScript','programming','fa-brands fa-js',35],['C','programming','fa-solid fa-code',60],['HTML & CSS','programming','fa-brands fa-html5',58],
  ['Ethical Hacking','security','fa-solid fa-user-secret',30],['Network Security','security','fa-solid fa-network-wired',30],['Web Security','security','fa-solid fa-shield-halved',29],['Vulnerability Assessment','security','fa-solid fa-magnifying-glass',50],['Linux','security','fa-brands fa-linux',55],['Cryptography','security','fa-solid fa-key',15],
  ['Git & GitHub','tools','fa-brands fa-git-alt',60],['Wireshark','tools','fa-solid fa-wave-square',22],['Nmap','tools','fa-solid fa-radar',20],['Burp Suite','tools','fa-solid fa-bug',20],['VirtualBox','tools','fa-solid fa-cube',52],['VS Code','tools','fa-solid fa-laptop-code',78],
  ['SQL','other','fa-solid fa-database',58],['REST APIs','other','fa-solid fa-plug',55],['LLM Integration','other','fa-solid fa-brain',48],['Prompt Engineering','other','fa-solid fa-wand-magic-sparkles',78]
];
const projects=[
   {title:'Personal Portfolio Website',cat:'web',label:'WEB DEVELOPMENT',demo:'#',desc:'A responsive, accessible portfolio with a distinctive cyber-security visual language.',tech:['HTML5','CSS3','Vanilla JS'],bg:'linear-gradient(135deg,#0d5963,#17315f)',problem:'A professional presence should show both personality and technical craft.',objective:'Build a fast, framework-free site that is easy to customize.',features:['Project modal','Responsive navigation','Scroll animations'],security:'No user data collection; contact form uses mailto only.',challenge:'Creating visual polish without third-party UI frameworks.',solution:'Used semantic HTML, reusable CSS patterns, and lightweight JavaScript.'},
   {title:'Wedding Invitation Website',cat:'web',label:'WEB DEVELOPMENT',demo:'https://wedding-invitation-rose-tau.vercel.app/',desc:'A digital wedding invitation website designed to provide event details and an interactive experience for guests. It is created for learning purpose.',tech:['Next.js','React.js','TypeScript','Tailwind CSS','Framer Motion','GSAP','GSAP ScrollTrigger','HTML5','CSS3','JavaScript','Lottie Animations','Responsive Web Design','Node.js','npm','Git','GitHub','Vercel'],bg:'linear-gradient(135deg,#7b1fa2,#ec4899)',problem:'Guests need a polished, mobile-friendly way to access invitation details and event information.',objective:'Create a beautiful, interactive wedding invitation experience for learning and presentation purposes.',features:['Elegant responsive design','Event information and schedule','Image gallery and animations','Mobile-friendly user interface'],security:'Built as a front-end learning project with no sensitive guest data handling.',challenge:'Balancing elegance and performance while keeping the experience interactive and responsive.',solution:'Used modern UI techniques, motion libraries, and a lightweight component structure.'},
 //{title:'Cyber Awareness Portal',cat:'cyber',label:'CYBER SECURITY',desc:'An approachable learning hub that turns safe online habits into daily practice.',tech:['HTML','CSS','JavaScript'],bg:'linear-gradient(135deg,#075c6d,#1b315a)',problem:'Security awareness resources can feel dense and disconnected from everyday online decisions.',objective:'Create an engaging, accessible portal for practical cyber safety learning.',features:['Interactive learning modules','Phishing awareness quiz','Responsive dashboard'],security:'Input validation patterns, privacy-first form design, and secure-content guidance.',challenge:'Making security topics feel useful rather than intimidating.',solution:'Used plain language, small learning steps, and scenario-led interactions.'},
 {title:'Vulnerability Reporting Portal',cat:'cyber',label:'CYBER SECURITY',demo:'https://example.com/vulnerability-reporting',statusLabel:'under devoloping',desc:'A structured concept for receiving, tracking, and responsibly triaging security reports.',tech:['JavaScript','REST API','UI/UX'],bg:'linear-gradient(135deg,#412063,#0c5261)',problem:'Teams need a clear, respectful route for responsible disclosure.',objective:'Design a transparent reporting experience that guides researchers and teams.',features:['Report intake workflow','Status tracking concept','Severity guidance'],security:'Designed around minimum data collection and safe disclosure principles.',challenge:'Balancing detailed reporting needs with a simple interface.',solution:'Created progressive disclosure and structured report fields.'},
 //{title:'Study Companion AI',cat:'ai',label:'AI / ML',desc:'A focused study assistant concept that helps students organize topics and practice.',tech:['JavaScript','LLM','APIs'],bg:'linear-gradient(135deg,#173875,#69318a)',problem:'Students often lose time organizing learning across multiple sources.',objective:'Offer a simple interface for guided study prompts and revision.',features:['Topic planner','Prompt templates','Revision checklist'],security:'Clear privacy notice and no storage in the front-end prototype.',challenge:'Keeping the product focused instead of building a generic chatbot.',solution:'Designed task-oriented flows around real student needs.'},
 //{title:'Network Traffic Analyzer',cat:'networking',label:'NETWORKING',desc:'A lab project exploring packet behaviour, protocols, and network visibility.',tech:['Wireshark','Python','Networking'],bg:'linear-gradient(135deg,#064a63,#263d73)',problem:'Raw packet data is difficult for beginners to interpret.',objective:'Document and visualize core traffic patterns from a controlled lab.',features:['Protocol inspection','Traffic summaries','Lab documentation'],security:'All testing is limited to an authorised local lab environment.',challenge:'Connecting theoretical networking concepts to real captures.',solution:'Created guided observations and repeatable lab notes.'}
];
const skillGrid=document.querySelector('#skills-grid'),projectGrid=document.querySelector('#projects-grid');
function renderSkills(filter='all'){skillGrid.innerHTML=skills.filter(s=>filter==='all'||s[1]===filter).map(s=>`<article class="skill-card glass"><div class="skill-top"><i class="${s[2]}"></i><small>${s[1]}</small></div><h3>${s[0]}</h3><div class="meter"><span style="--level:${s[3]}%"></span></div></article>`).join('')}
function renderProjects(filter='all'){projectGrid.innerHTML=projects.map((p,i)=>({...p,index:i})).filter(p=>filter==='all'||p.cat===filter).map(p=>`<article class="project-card glass tilt"><div class="project-visual" style="--project-bg:${p.bg}"><span>${p.label}</span>${p.statusLabel?`<span class="project-status">${p.statusLabel}</span>`:''}</div><div class="project-body"><h3>${p.title}</h3><p>${p.desc}</p><div class="tags">${p.tech.map(t=>`<span>${t}</span>`).join('')}</div><div class="project-links"><a href="#" target="_blank"><i class="fa-brands fa-github"></i> GitHub</a>${p.demo?`<a href="${p.demo}" target="_blank">Demo</a>`:'<span class="demo-disabled">Demo</span>'}<button class="details" data-project="${p.index}">Details <i class="fa-solid fa-arrow-right"></i></button></div></div></article>`).join('');applyTilt()}
renderSkills();renderProjects();
document.querySelectorAll('[data-skill-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-skill-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSkills(b.dataset.skillFilter)}));
document.querySelectorAll('[data-project-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-project-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProjects(b.dataset.projectFilter)}));
const modal=document.querySelector('#project-modal');projectGrid.addEventListener('click',e=>{const button=e.target.closest('.details');if(!button)return;const p=projects[button.dataset.project];document.querySelector('#modal-content').innerHTML=`<div class="modal-inner"><p class="eyebrow">${p.label} / PROJECT DETAIL</p><h2>${p.title}</h2><p>${p.desc}</p><div class="modal-grid"><div class="modal-box"><h3>Problem & objective</h3><p><b>Problem:</b> ${p.problem}</p><p><b>Objective:</b> ${p.objective}</p></div><div class="modal-box"><h3>Security approach</h3><p>${p.security}</p><h3>Challenge & solution</h3><p>${p.challenge} ${p.solution}</p></div></div><div class="modal-box"><h3>Key features</h3><div class="tags">${p.features.map(f=>`<span>${f}</span>`).join('')}</div></div><p class="tags" style="margin-top:16px">${p.tech.map(t=>`<span>${t}</span>`).join('')}</p><a class="modal-link" href="#" target="_blank"><i class="fa-brands fa-github"></i> GitHub repository</a>${p.demo?`<a class="modal-link" href="${p.demo}" target="_blank">Live demo <i class="fa-solid fa-arrow-up-right-from-square"></i></a>`:'<span class="modal-link disabled">No demo</span>'}</div>`;modal.showModal()});document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
const nav=document.querySelector('.nav-wrap'),progress=document.querySelector('.scroll-progress'),backTop=document.querySelector('.back-top');window.addEventListener('scroll',()=>{const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${y/max*100}%`;nav.classList.toggle('scrolled',y>20);backTop.classList.toggle('show',y>600)},{passive:true});backTop.onclick=()=>scrollTo({top:0,behavior:'smooth'});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');if(e.target.querySelector('[data-count]'))e.target.querySelectorAll('[data-count]').forEach(counter=>{if(counter.dataset.done)return;counter.dataset.done=1;let n=0,target=+counter.dataset.count;let timer=setInterval(()=>{n=Math.min(target,n+Math.ceil(target/35));counter.textContent=n+(counter.dataset.suffix||'');if(n===target)clearInterval(timer)},30)})}}),{threshold:.12});document.querySelectorAll('.reveal,.stats').forEach(el=>observer.observe(el));
const sections=document.querySelectorAll('main section[id]'),navLinks=document.querySelectorAll('.nav-links a');sections.forEach(s=>new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)navLinks.forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))}),{rootMargin:'-35% 0px -55%'}).observe(s));
const toggle=document.querySelector('.menu-toggle'),links=document.querySelector('.nav-links');toggle.onclick=()=>{let open=links.classList.toggle('open');toggle.setAttribute('aria-expanded',open);toggle.innerHTML=`<i class="fa-solid fa-${open?'xmark':'bars'}"></i>`};links.querySelectorAll('a').forEach(a=>a.onclick=()=>links.classList.remove('open'));
let role='Cyber Security Enthusiast | B.Tech CSE (Cyber Security) Student',typed=document.querySelector('#typed-role'),i=0;(function type(){typed.textContent=role.slice(0,++i);if(i<role.length)setTimeout(type,30)})();
document.addEventListener('pointermove',e=>document.querySelector('.cursor-glow').style.transform=`translate(${e.clientX}px,${e.clientY}px)`);document.addEventListener('pointerdown',e=>{let r=document.createElement('span');r.className='click-ripple';r.style.cssText=`position:fixed;left:${e.clientX}px;top:${e.clientY}px;width:12px;height:12px;border:1px solid #5eead4;border-radius:50%;pointer-events:none;z-index:30;animation:ripple .7s ease-out forwards`;document.body.append(r);setTimeout(()=>r.remove(),700)});
const style=document.createElement('style');style.textContent='@keyframes ripple{to{transform:translate(-75px,-75px) scale(13);opacity:0}}';document.head.append(style);
function applyTilt(){document.querySelectorAll('.tilt').forEach(el=>el.onpointermove=e=>{if(matchMedia('(pointer:coarse)').matches)return;let r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(700px) rotateX(${y*-5}deg) rotateY(${x*5}deg) translateY(-4px)`});document.querySelectorAll('.tilt').forEach(el=>el.onpointerleave=()=>el.style.transform='')};
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();let n=document.querySelector('#name').value.trim(),m=document.querySelector('#message').value.trim(),email=document.querySelector('#email').value.trim();location.href=`mailto:ameensham786@gmail.com?subject=${encodeURIComponent('Portfolio enquiry from '+n)}&body=${encodeURIComponent(m+'\n\nReply to: '+email)}`;document.querySelector('#form-note').textContent='Your email app should open with a pre-filled message.'});document.querySelector('#year').textContent=new Date().getFullYear();
